(function attachOutreachPack(global) {
  "use strict";

  var namespace = global.FA = global.FA || {};
  var REVIEWED_ON = "2026-05-29";
  var SOURCE_NOTE = "Summer 2026 outreach pack seeded from local deep-research-report.md and preview.html. Verify official pages before outreach or bid work.";
  var MARKET = {
    earlyJune: "Early-June country and cross-genre burst",
    peakUrban: "Late-July and early-August urban mega-fest run",
    laborDay: "Labor Day corridor",
    lateSeptember: "Dense late-September rock, EDM, and heritage block"
  };

  function parseIso(value) {
    var parts = String(value || "").split("-").map(Number);
    return new Date(parts[0], parts[1] - 1, parts[2] || 1, 12);
  }

  function iso(date) {
    return date.getFullYear() + "-" + String(date.getMonth() + 1).padStart(2, "0") + "-" + String(date.getDate()).padStart(2, "0");
  }

  function sessionsForRanges(ranges) {
    var weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    var sessions = [];
    ranges.forEach(function eachRange(range, rangeIndex) {
      var cursor = parseIso(range.start);
      var end = parseIso(range.end || range.start);
      var day = 1;
      while (cursor <= end) {
        var prefix = range.label || (ranges.length > 1 ? "Window " + (rangeIndex + 1) : "Festival");
        sessions.push({
          y: weekdays[cursor.getDay()],
          d: iso(cursor),
          t: range.time || null,
          o: range.artist || null,
          s: prefix + " Day " + day
        });
        cursor.setDate(cursor.getDate() + 1);
        day += 1;
      }
    });
    return sessions;
  }

  function mapEvent(event) {
    return {
      id: event.id,
      name: event.name,
      team: event.genre,
      city: event.city,
      roof: event.setting,
      tier: event.tier,
      color: event.color,
      note: event.productionNotes,
      ticketApproach: event.ticketUrl ? "Use the official ticket link and verify current sale status before outreach." : "Verify ticketing and public intake paths before outreach.",
      transitNote: event.transitNote || "Confirm venue access, parking, rideshare, and lodging before making a field plan.",
      specialEvents: event.signals.slice(0, 5),
      searchMeta: {
        localName: event.shortName || event.name,
        region: event.region
      },
      officialUrl: event.officialUrl,
      lastReviewed: REVIEWED_ON,
      sourceNote: SOURCE_NOTE,
      dateConfidence: "outreach-review",
      ops: {
        packId: "summer-2026-outreach",
        status: "Confirmed - verify before outreach",
        region: event.region,
        venue: event.venue,
        organizer: event.organizer,
        headliners: event.headliners,
        attendance: event.attendance || "",
        publicContact: event.publicContact || "",
        eventHours: event.eventHours || "",
        loadIn: event.loadIn || "Not public; use event hours, early-entry, camping, and venue notes as operating proxies.",
        productionNotes: event.productionNotes,
        opsModel: event.opsModel,
        marketWindow: event.marketWindow,
        outreachPriority: event.priority,
        ticketUrl: event.ticketUrl || "",
        opportunitySignals: event.signals,
        watchItems: event.watchItems || [],
        sources: [
          { label: "Official site", url: event.officialUrl },
          event.ticketUrl ? { label: "Tickets", url: event.ticketUrl } : null
        ].filter(Boolean)
      },
      sessions: sessionsForRanges(event.ranges)
    };
  }

  var EVENTS = [
    {
      id: "governors-ball",
      name: "The Governors Ball Music Festival",
      shortName: "Gov Ball",
      ranges: [{ start: "2026-06-05", end: "2026-06-07" }],
      city: "Queens, NY",
      region: "Northeast",
      venue: "Flushing Meadows Corona Park",
      genre: "Pop - Hip hop - Multigenre",
      setting: "Urban",
      tier: "A",
      color: "#2563EB",
      headliners: "Lorde, Stray Kids, ASAP Rocky; 60+ artists across three stages",
      organizer: "Governors Ball / C3 Presents",
      officialUrl: "https://www.governorsballmusicfestival.com/",
      ticketUrl: "https://www.governorsballmusicfestival.com/tickets/",
      publicContact: "partners@govball.com; cabana and concierge sales routes noted in public materials",
      productionNotes: "Urban park mega-fest with VIP, GA+, private suites, cabanas, wristbands, lockers, hotel packages, and Queens Night Market food tie-ins.",
      opsModel: "Urban park mega-fest",
      marketWindow: MARKET.earlyJune,
      priority: "High",
      signals: ["Partnership email", "Premium hospitality", "Food tie-ins", "Three-stage park build", "Hotel packages"]
    },
    {
      id: "cma-fest",
      name: "CMA Fest",
      ranges: [{ start: "2026-06-04", end: "2026-06-07" }],
      city: "Nashville, TN",
      region: "South",
      venue: "Nissan Stadium plus downtown daytime stages",
      genre: "Country",
      setting: "Mixed",
      tier: "A",
      color: "#D97706",
      headliners: "Bailey Zimmerman, Blake Shelton, Jason Aldean, Keith Urban, Lainey Wilson, Luke Bryan, Tim McGraw",
      organizer: "Country Music Association",
      officialUrl: "https://cmafest.com/",
      ticketUrl: "https://cmafest.com/tickets/",
      productionNotes: "Citywide country footprint with Nissan Stadium night shows, Fan Fair X, free daytime stages, premium packages, and multi-site guest operations.",
      opsModel: "Citywide stadium plus downtown stages",
      marketWindow: MARKET.earlyJune,
      priority: "High",
      signals: ["Citywide footprint", "Stadium shows", "Fan Fair X", "Premium packages", "Free daytime stages"]
    },
    {
      id: "carolina-country-music-fest",
      name: "Carolina Country Music Fest",
      ranges: [{ start: "2026-06-04", end: "2026-06-07" }],
      city: "Myrtle Beach, SC",
      region: "South",
      venue: "Downtown Myrtle Beach / beachfront festival site",
      genre: "Country",
      setting: "Waterfront",
      tier: "B",
      color: "#F59E0B",
      headliners: "Post Malone, Luke Bryan, Blake Shelton, Riley Green; 40+ artist bill",
      organizer: "Carolina Country Music Fest",
      officialUrl: "https://carolinacountrymusicfest.com/",
      ticketUrl: "https://carolinacountrymusicfest.com/tickets/",
      productionNotes: "Beachside country festival with five-stage public positioning, app-based schedule flow, re-entry, and a high-traffic beachfront guest-services footprint.",
      opsModel: "Beachfront multi-stage festival",
      marketWindow: MARKET.earlyJune,
      priority: "Medium-high",
      signals: ["Five stages", "Beachfront site", "App schedule", "Re-entry", "Volunteer pathway"]
    },
    {
      id: "bonnaroo",
      name: "Bonnaroo Music and Arts Festival",
      ranges: [{ start: "2026-06-11", end: "2026-06-14" }],
      city: "Manchester, TN",
      region: "South",
      venue: "The Farm / Great Stage Park",
      genre: "Indie - Jam - Electronic",
      setting: "Camping",
      tier: "S",
      color: "#22C55E",
      headliners: "The Strokes, RUFUS DU SOL, Noah Kahan, Skrillex",
      organizer: "Bonnaroo / Live Nation ecosystem",
      officialUrl: "https://www.bonnaroo.com/",
      ticketUrl: "https://www.bonnaroo.com/tickets",
      productionNotes: "Large 700-acre camping environment with hotel, locker, map, wristband, accommodation, and guest-services infrastructure signals.",
      opsModel: "Camping and destination build",
      marketWindow: MARKET.earlyJune,
      priority: "High",
      signals: ["700-acre farm", "Camping", "Lockers", "Hotels", "Accommodation pages"]
    },
    {
      id: "summerfest",
      name: "Summerfest",
      ranges: [
        { start: "2026-06-18", end: "2026-06-20", label: "Weekend 1" },
        { start: "2026-06-25", end: "2026-06-27", label: "Weekend 2" },
        { start: "2026-07-02", end: "2026-07-04", label: "Weekend 3" }
      ],
      city: "Milwaukee, WI",
      region: "Midwest",
      venue: "Henry Maier Festival Park",
      genre: "Broad-genre urban lakefront",
      setting: "Urban",
      tier: "S",
      color: "#0891B2",
      headliners: "600 artists across 12 permanent stages; 2026 reveal led with Garth Brooks amphitheater kick-off",
      organizer: "Milwaukee World Festival, Inc.",
      officialUrl: "https://www.summerfest.com/",
      ticketUrl: "https://www.summerfest.com/tickets/",
      productionNotes: "Permanent festival campus with amphitheater ticketing, BMO Pavilion reserved seats, pit wristbands, premium decks, and multiple amphitheater bookings layered over the festival.",
      opsModel: "Permanent urban festival campus",
      marketWindow: MARKET.earlyJune,
      priority: "High",
      signals: ["12 permanent stages", "Amphitheater bookings", "Reserved seats", "Premium decks", "Multi-weekend run"]
    },
    {
      id: "electric-forest",
      name: "Electric Forest",
      ranges: [{ start: "2026-06-25", end: "2026-06-28" }],
      city: "Rothbury, MI",
      region: "Midwest",
      venue: "Double JJ Ranch and Resort",
      genre: "EDM - Jam - Camping",
      setting: "Camping",
      tier: "A",
      color: "#16A34A",
      headliners: "GRiZ, Illenium, Chris Lake, Kaskade, The String Cheese Incident",
      organizer: "Electric Forest",
      officialUrl: "https://www.electricforest.com/",
      ticketUrl: "https://www.electricforest.com/passes/",
      productionNotes: "Camping hybrid with official camping, hotel, shuttle, ticketing, and early-entry music signals before the main festival weekend.",
      opsModel: "Camping and destination build",
      marketWindow: MARKET.earlyJune,
      priority: "High",
      signals: ["Camping", "Hotel/shuttle pages", "Early-entry music", "Large ranch site", "Guest-services complexity"]
    },
    {
      id: "essence-festival-of-culture",
      name: "ESSENCE Festival of Culture",
      ranges: [{ start: "2026-07-03", end: "2026-07-05" }],
      city: "New Orleans, LA",
      region: "South",
      venue: "New Orleans citywide programming and evening concert series",
      genre: "R&B - Hip hop - Culture",
      setting: "Mixed",
      tier: "A",
      color: "#EC4899",
      headliners: "Cardi B, Kehlani, Babyface, Brandy & Monica, Public Enemy",
      organizer: "ESSENCE",
      officialUrl: "https://www.essencefestival.com/",
      ticketUrl: "https://www.essencefestival.com/",
      productionNotes: "Festival plus conference/cultural summit with 20+ curated experiences spanning music, art, wellness, style, cuisine, and commerce.",
      opsModel: "Culture summit plus concert series",
      marketWindow: MARKET.earlyJune,
      priority: "Medium-high",
      signals: ["20+ experiences", "Citywide programming", "Commerce", "Cuisine", "Evening concerts"]
    },
    {
      id: "newport-folk-festival",
      name: "Newport Folk Festival",
      ranges: [{ start: "2026-07-24", end: "2026-07-26" }],
      city: "Newport, RI",
      region: "Northeast",
      venue: "Fort Adams State Park",
      genre: "Folk - Americana",
      setting: "Waterfront",
      tier: "A",
      color: "#0EA5E9",
      headliners: "Hayley Williams, Ms. Lauryn Hill, Courtney Barnett, and others from public lineup coverage",
      organizer: "Newport Festivals Foundation",
      officialUrl: "https://newportfolk.org/",
      ticketUrl: "https://newportfolk.org/tickets/",
      productionNotes: "Destination nonprofit festival with no on-site camping, no re-entry, high lodging pressure, and a clean premium guest-ops profile.",
      opsModel: "Civic/nonprofit destination festival",
      marketWindow: MARKET.peakUrban,
      priority: "Medium-high",
      signals: ["Nonprofit producer", "No on-site camping", "No re-entry", "Destination lodging", "Fort Adams rules"]
    },
    {
      id: "lollapalooza",
      name: "Lollapalooza",
      ranges: [{ start: "2026-07-30", end: "2026-08-02" }],
      city: "Chicago, IL",
      region: "Midwest",
      venue: "Grant Park",
      genre: "Pop - Rock - Hip hop",
      setting: "Urban",
      tier: "S",
      color: "#7C3AED",
      headliners: "Charli XCX, Lorde, Tate McRae, JENNIE, John Summit, The Smashing Pumpkins, The xx, Olivia Dean",
      organizer: "C3 Presents",
      officialUrl: "https://www.lollapalooza.com/",
      ticketUrl: "https://www.lollapalooza.com/tickets",
      publicContact: "press@c3presents.com; food-vendor, sponsorship, and creator routes noted in public materials",
      productionNotes: "Major park build with 100+ artists across eight stages, aftershows, hotel packages, sponsor routes, and strong city economic footprint.",
      opsModel: "Urban park mega-fest",
      marketWindow: MARKET.peakUrban,
      priority: "High",
      signals: ["Eight stages", "Food vendor form", "Sponsorship form", "Creator route", "Aftershows"]
    },
    {
      id: "newport-jazz-festival",
      name: "Newport Jazz Festival",
      ranges: [{ start: "2026-07-31", end: "2026-08-02" }],
      city: "Newport, RI",
      region: "Northeast",
      venue: "Fort Adams State Park",
      genre: "Jazz - Soul",
      setting: "Waterfront",
      tier: "A",
      color: "#1F2937",
      headliners: "Herbie Hancock, Kamasi Washington, Jon Batiste, Vulfpeck",
      organizer: "Newport Festivals Foundation",
      officialUrl: "https://newportjazz.org/",
      ticketUrl: "https://newportjazz.org/tickets/",
      productionNotes: "Heritage jazz destination with official contact/event info, daily schedules pending in research, and site/travel rules similar to Newport Folk.",
      opsModel: "Civic/nonprofit destination festival",
      marketWindow: MARKET.peakUrban,
      priority: "Medium-high",
      signals: ["Nonprofit producer", "Official contact", "Fort Adams site", "Destination draw", "Schedule pending"]
    },
    {
      id: "hard-summer",
      name: "HARD Summer",
      ranges: [{ start: "2026-08-01", end: "2026-08-02", time: "2:00 PM" }],
      city: "Inglewood, CA",
      region: "West",
      venue: "Hollywood Park adjacent to SoFi Stadium",
      genre: "Electronic - Hip hop",
      setting: "Urban",
      tier: "A",
      color: "#FACC15",
      headliners: "Feid, Gesaffelstein, Four Tet, Dom Dolla, Kaytranada, and others",
      organizer: "Insomniac",
      officialUrl: "https://www.hardsummer.com/",
      ticketUrl: "https://www.hardsummer.com/tickets/",
      publicContact: "partnerships@insomniac.com; media request form and non-food vendor application noted in public materials",
      eventHours: "2:00 PM-10:00 PM both days",
      productionNotes: "EDM/hip-hop crossover event with exact public hours, Insomniac partnership/vendor infrastructure, and Hollywood Park site logistics.",
      opsModel: "Urban stadium-district electronic festival",
      marketWindow: MARKET.peakUrban,
      priority: "High",
      signals: ["Partnership email", "Media form", "Non-food vendor app", "Exact public hours", "Stadium district"]
    },
    {
      id: "outside-lands",
      name: "Outside Lands",
      ranges: [{ start: "2026-08-07", end: "2026-08-09" }],
      city: "San Francisco, CA",
      region: "West",
      venue: "Golden Gate Park",
      genre: "Indie - Pop - Electronic",
      setting: "Urban",
      tier: "S",
      color: "#F59E0B",
      headliners: "Charli XCX, Tyler, The Creator, Hozier, RUFUS DU SOL",
      organizer: "Outside Lands",
      officialUrl: "https://sfoutsidelands.com/",
      ticketUrl: "https://sfoutsidelands.com/tickets/",
      publicContact: "sponsor@sfoutsidelands.com, press@sfoutsidelands.com, access@sfoutsidelands.com; Bay Area food-vendor application noted",
      productionNotes: "Hospitality-rich park festival with front-of-stage access, stage-to-stage golf-cart movement, concierge service, shuttles, SOMA, and Golden Gate Club environments.",
      opsModel: "Urban park mega-fest",
      marketWindow: MARKET.peakUrban,
      priority: "High",
      signals: ["Sponsor email", "Press email", "Access email", "Food vendor app", "Premium hospitality"]
    },
    {
      id: "north-coast-music-festival",
      name: "North Coast Music Festival",
      ranges: [{ start: "2026-09-04", end: "2026-09-06", time: "2:00 PM" }],
      city: "Bridgeview, IL",
      region: "Midwest",
      venue: "SeatGeek Stadium",
      genre: "EDM",
      setting: "Urban",
      tier: "B",
      color: "#8B5CF6",
      headliners: "75+ DJs on 6 stages; public materials list FISHER, DEORRO, Ganja White Night, and more",
      organizer: "North Coast Music Festival",
      officialUrl: "https://www.northcoastfestival.com/",
      ticketUrl: "https://www.northcoastfestival.com/tickets/",
      publicContact: "sponsor@northcoastfestival.com; vendor and media pages noted in public materials",
      eventHours: "Public FAQ lists 2 PM starts plus parking/will-call windows",
      productionNotes: "Stadium plus adjacent turf-field EDM event with no re-entry, official parking/will-call windows, sponsor route, and vendor/media pages.",
      opsModel: "Stadium plus turf-field electronic festival",
      marketWindow: MARKET.laborDay,
      priority: "High",
      signals: ["Sponsor email", "Vendor page", "Media page", "Six stages", "Parking/will-call windows"],
      watchItems: ["2026 map and set times release closer to festival"]
    },
    {
      id: "detroit-jazz-festival",
      name: "Detroit Jazz Festival",
      ranges: [{ start: "2026-09-04", end: "2026-09-07" }],
      city: "Detroit, MI",
      region: "Midwest",
      venue: "Hart Plaza",
      genre: "Jazz",
      setting: "Urban",
      tier: "A",
      color: "#0F766E",
      headliners: "Ron Carter, Bob James, Ravi Coltrane, Artemis, Kurt Elling & Yellowjackets",
      organizer: "Detroit Jazz Festival Foundation",
      officialUrl: "https://www.detroitjazzfest.org/",
      ticketUrl: "https://www.detroitjazzfest.org/",
      eventHours: "Official FAQ publishes Hart Plaza opening and closing times",
      productionNotes: "Free nonprofit jazz event with VIP pass pages, Hart Plaza public hours, and one of the clearest public livestream/broadcast signals in the set.",
      opsModel: "Civic/nonprofit broadcast-visible festival",
      marketWindow: MARKET.laborDay,
      priority: "High",
      signals: ["Free event", "VIP pass page", "Public hours", "Live video streams", "Nonprofit producer"]
    },
    {
      id: "bumbershoot",
      name: "Bumbershoot",
      ranges: [{ start: "2026-09-05", end: "2026-09-06" }],
      city: "Seattle, WA",
      region: "West",
      venue: "Seattle Center Campus",
      genre: "Alt - Pop - Arts",
      setting: "Urban",
      tier: "A",
      color: "#2563EB",
      headliners: "Death Cab for Cutie, Turnstile, Blood Orange, Lucy Dacus, Orville Peck, Chase & Status",
      organizer: "Bumbershoot",
      officialUrl: "https://bumbershoot.com/",
      ticketUrl: "https://bumbershoot.com/tickets/",
      publicContact: "Press contacts and food-vendor application noted in public materials",
      productionNotes: "Multidisciplinary arts and music build with restaurants, comedy, fashion, short films, wrestling, skateboarding, BMX, press contacts, and vendor applications.",
      opsModel: "Urban arts campus festival",
      marketWindow: MARKET.laborDay,
      priority: "Medium-high",
      signals: ["Press contacts", "Food vendor app", "Multidisciplinary programming", "Seattle Center campus", "Arts overlay"]
    },
    {
      id: "riot-fest",
      name: "Riot Fest",
      ranges: [{ start: "2026-09-18", end: "2026-09-20" }],
      city: "Chicago, IL",
      region: "Midwest",
      venue: "Douglass Park",
      genre: "Punk - Alt - Emo",
      setting: "Urban",
      tier: "A",
      color: "#111827",
      headliners: "Tool, Alanis Morissette, Morrissey, Twenty One Pilots, Pierce The Veil",
      organizer: "Riot Fest",
      officialUrl: "https://riotfest.org/",
      ticketUrl: "https://riotfest.org/tickets/",
      publicContact: "Community/partnership form noted in public materials",
      productionNotes: "Fresh late-May lineup signal with gates/show-day listings and public partnership/community pitch; daily schedule still pending in research.",
      opsModel: "Urban park rock festival",
      marketWindow: MARKET.lateSeptember,
      priority: "Medium-high",
      signals: ["Fresh lineup", "Partnership/community form", "Show-day listings", "Park build", "Late-September density"],
      watchItems: ["Daily schedule pending after May 28 lineup release"]
    },
    {
      id: "sea-hear-now",
      name: "Sea.Hear.Now Festival",
      ranges: [{ start: "2026-09-19", end: "2026-09-20" }],
      city: "Asbury Park, NJ",
      region: "Northeast",
      venue: "North Beach / boardwalk footprint",
      genre: "Rock - Alt - Surf",
      setting: "Waterfront",
      tier: "A",
      color: "#06B6D4",
      headliners: "Mumford & Sons, The Strokes, The Offspring, Chaka Khan",
      organizer: "Sea.Hear.Now",
      officialUrl: "https://www.seahearnowfestival.com/",
      ticketUrl: "https://www.seahearnowfestival.com/tickets",
      productionNotes: "Beach and boardwalk event with music, art, and a live surf competition between Surf and Sand stages, creating an operational wrinkle beyond a standard beach fest.",
      opsModel: "Beachfront music, surf, and art festival",
      marketWindow: MARKET.lateSeptember,
      priority: "Medium-high",
      signals: ["Surf competition", "Beachfront stages", "Boardwalk footprint", "Art overlay", "Late-September density"]
    },
    {
      id: "bourbon-and-beyond",
      name: "Bourbon & Beyond",
      ranges: [{ start: "2026-09-24", end: "2026-09-27" }],
      city: "Louisville, KY",
      region: "South",
      venue: "Highland Festival Grounds at Kentucky Expo Center",
      genre: "Rock - Americana - Country",
      setting: "Outdoor",
      tier: "A",
      color: "#92400E",
      headliners: "Foo Fighters, Mumford & Sons, Chris Stapleton, Dave Matthews Band, Queens of the Stone Age",
      organizer: "Danny Wimmer Presents",
      officialUrl: "https://bourbonandbeyond.com/",
      ticketUrl: "https://bourbonandbeyond.com/passes/",
      productionNotes: "Large-format DWP weekender with camping, hotel packages, app-based schedule support, sponsor-rich environment, and food-and-beverage integration.",
      opsModel: "Large-format DWP destination weekender",
      marketWindow: MARKET.lateSeptember,
      priority: "High",
      signals: ["DWP ecosystem", "Camping", "Hotel packages", "Sponsor-rich", "Food and beverage program"]
    },
    {
      id: "oceans-calling",
      name: "Oceans Calling",
      ranges: [{ start: "2026-09-25", end: "2026-09-27", time: "12:00 PM" }],
      city: "Ocean City, MD",
      region: "Northeast",
      venue: "Ocean City Inlet / boardwalk",
      genre: "Rock - Pop",
      setting: "Waterfront",
      tier: "A",
      color: "#0EA5E9",
      headliners: "Dave Matthews Band, Twenty One Pilots, Mumford & Sons, Gwen Stefani, Matchbox Twenty",
      organizer: "Oceans Calling",
      officialUrl: "https://www.oceanscallingfestival.com/",
      ticketUrl: "https://www.oceanscallingfestival.com/tickets",
      publicContact: "partners@oceanscallingfestival.com; info@oceanscallingfestival.com via support materials",
      eventHours: "12:00 PM-11:00 PM daily",
      productionNotes: "Boardwalk festival with 40+ performances on three stages, Jolly Roger At The Pier rides inside grounds, public hours, and sponsorship contact.",
      opsModel: "Boardwalk destination festival",
      marketWindow: MARKET.lateSeptember,
      priority: "High",
      signals: ["Sponsorship email", "Public hours", "Three stages", "Boardwalk footprint", "Ride integration"]
    },
    {
      id: "portola",
      name: "Portola Music Festival",
      ranges: [{ start: "2026-09-26", end: "2026-09-27" }],
      city: "San Francisco, CA",
      region: "West",
      venue: "Pier 80",
      genre: "Electronic",
      setting: "Mixed",
      tier: "A",
      color: "#9333EA",
      headliners: "Robyn, Dog Blood, Swedish House Mafia, Tiesto, Zara Larsson",
      organizer: "Goldenvoice",
      officialUrl: "https://portolamusicfestival.com/",
      ticketUrl: "https://portolamusicfestival.com/passes/",
      productionNotes: "Pier 80 electronic event with indoor/outdoor official FAQ positioning and a premium Captain's Club signal around Warehouse-stage access and hospitality.",
      opsModel: "Indoor/outdoor pier electronic festival",
      marketWindow: MARKET.lateSeptember,
      priority: "High",
      signals: ["Goldenvoice", "Indoor/outdoor site", "Captain's Club", "Warehouse-stage access", "Premium hospitality"]
    }
  ];

  namespace.outreachPack = {
    app: "Festival Atlas",
    packId: "summer-2026-outreach",
    label: "Summer 2026 Outreach Pack",
    generatedAt: REVIEWED_ON,
    description: "Confirmed public-facing June-September 2026 music events with ops, vendor, sponsor, and production outreach signals.",
    overwriteSchedules: false,
    festivals: EVENTS.map(mapEvent),
    series: [
      "SummerStage",
      "Millennium Park Summer Music Series",
      "Chicago House Music Festival and Conference",
      "Chicago Blues Festival",
      "Outlaw Music Festival Tour",
      "Levitt Music Series network"
    ],
    watchlist: [
      "Lost Lands",
      "Louder Than Life",
      "Riot Fest daily schedule",
      "North Coast 2026 map and set times",
      "Chicago House Music Festival full 2026 schedule"
    ]
  };
})(window);
